.test:
  before_script:
    - cd back
    - npm install
  stage: test
  tags:
    - activiot-mac
  only:
    - dev
.build:
  before_script:
    - cd back
    - npm install
  stage: build
  tags:
    - activiot-mac
  only:
    - dev
test_api:
  extends: .test
  script:
    - npm run ci


build_api:
  extends: .build
  script:
    - tsc
