.test:
  before_script:
    - cd back
    - npm install
  stage: test
  tags:
    - activiot-mac

.build:
  before_script:
    - cd back
    - npm install
  stage: build
  tags:
    - activiot-mac

test_api:
  extends: .test
  script:
    - npm run ci
  only:
    - dev

test_cool:
  extends: .build
  script:
    - tsc
