stages:
  - build
  - deploy

.build:
  before_script:
    - cd back/microservices/src
  stage: build
  tags:
    - activiot
  only:
    - master
  rules:
    - when: on_success

.deploy:
  before_script:
    - cd back/microservices/src
  stage: deploy
  tags:
    - activiot
  only:
    - master
  rules:
    - when: on_success

build_auth:
  extends: .build
  script:
    - cd auth
    - docker build -t activiot/logger:latest .
    - docker push activiot/logger:latest

build_beacon:
  extends: .build
  script:
    - cd beacon
    - docker build -t activiot/beacon:latest .
    - docker push activiot/beacon:latest

build_client:
  extends: .build
  script:
    - cd client
    - npm install
    - npm run build
    - docker build -t activiot/client:latest .
    - docker push activiot/client:latest
build_logger:
  extends: .build
  script:
    - cd logger
    - docker build -t activiot/logger:latest .
    - docker push activiot/logger:latest

build_webserver:
  extends: .build
  script:
    - cd webserver
    - docker build -t activiot/webserver:latest .
    - docker push activiot/webserver:latest

deploy_auth:
  stage: deploy
  script:
    - cd auth
    - curl -v --header "Content-Type: application/json" --request POST -d nomad.json $NOMAD_API


deploy_beacon:
  stage: deploy
  script:
    - cd beacon
    - curl -v --header "Content-Type: application/json" --request POST -d nomad.json $NOMAD_API

deploy_client:
  stage: deploy
  script:
    - cd client
    - curl -v --header "Content-Type: application/json" --request POST -d nomad.json $NOMAD_API

deploy_logger:
  stage: deploy
  script:
    - cd logger
    - curl -v --header "Content-Type: application/json" --request POST -d nomad.json $NOMAD_API

deploy_webserver:
  stage: deploy
  script:
    - cd webserver
    - curl -v --header "Content-Type: application/json" --request POST -d nomad.json $NOMAD_API
