.tests:
  script:
    - echo 'coucou'
  stage: test
  tags:
    - activiot-mac

test_de_plaiplai:
  extends: .tests
  script:
    - echo 'bonjour'
  after_script:
    - echo 're bonjour'
  only:
    - dev

test_de_plaiplai_2:
  extends: .tests

test_cool:
  stage: build
  script:
    - echo 'hello'
  tags:
    - activiot-mac