version: 2.1
executors:
  my-executor:
    docker:
      - image: cypress/base
    working_directory: ~/project
    environment:
      PRODUCTION: false
      PROJECT_NAME: beaconsprojet
      PROJECT_VERSION: 1.0
      GIT: https://github.com/issarompion/beaconsproject.git
      DB_PORT: 27017
      DB_URL: mongodb://localhost
      DB_NAME: beaconsproject
      API_URL: localhost
      API_PORT: 3000
      KAFKA_URL: localhost
      KAFKA_PORT: 9092
      KAFKA_TOPIC_AUTH: auth
      KAFKA_TOPIC_BEACON: beacon
      KAFKA_TOPIC_CLIENT: client
      KAFKA_TOPIC_CONTENT: content
      KAFKA_TOPIC_LOGGER: logger
      KAFKA_REQUEST: req
      KAFKA_RESPONSE: res
      KAFKA_ACTION_LIST: list
      KAFKA_ACTION_READ: read
      KAFKA_ACTION_UPDATE: update
      KAFKA_ACTION_DELETE: delete
      KAFKA_ACTION_CREATE: create
      KAFKA_ACTION_LOGIN: login
      KAFKA_ACTION_LOGOUT: logout
      JWT_KEY: beaconsproject
jobs:
  pre-build:
    executor: my-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
        name: Install Docker client
        command: |
          set -x
          if [ ! -f docker-17.03.0-ce.tgz ]; then
            curl -sLO https://download.docker.com/linux/static/stable/x86_64/docker-17.03.0-ce.tgz
          fi
          tar -xz -C /tmp -f docker-17.03.0-ce.tgz
          mv /tmp/docker/* /usr/bin
      - run: set > ".env"
      - run: cat .env
      - run: npm install

  build-test-back:
    executor: my-executor
    steps:
      - run: sh scripts/build_back.sh $DOCKERHUB_USERNAME $PROJECT_VERSION $GIT $API_PORT
      - run: sh scripts/run_back.sh $DOCKERHUB_USERNAME $PROJECT_VERSION $API_PORT
      - run: ./node_modules/.bin/wait-on http://$API_URL:$API_PORT && npm run cy:run:back

  deploy-back:
    executor: my-executor
      steps:
        - checkout
        - run: echo "$DOCKERHUB_PASS" && echo "$DOCKERHUB_USERNAME"

  build-test-app:
    executor: my-executor
    steps: 
      - checkout
      - run: npm build:app
      - run: npm run test:app
  
  build-test-beaconer:
    executor: my-executor
    steps:
      - checkout
      - run: npm build:app
      - run: npm run test:beaconer

workflows:
  version: 2
  build-test-deploy:
      jobs:
        - pre-build
        - build-test-back:
            requires:
              - pre-build
        - deploy-back:
            requires:
              - build-test-back

        - build-test-app
            requires:
              - pre-build
        - build-test-beaconer
            requires:
              - pre-build