version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    docker: 
      # DLC does nothing here, its caching depends on commonality of the image layers.
      - image: circleci/node:9.8.0-stretch-browsers 
      - image: wurstmeister/zookeeper
      - image: wurstmeister/kafka:latest
      environment:
        KAFKA_ADVERTISED_HOST_NAME: localhost
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_CREATE_TOPICS: "auth:1:1,client:1:1,beacon:1:1,content:1:1,logger:1:1"
        KAFKA_TOPIC_BEACON: beacon
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: export PROJECT_PATH=$(pwd)
            - run: printenv
            - run: docker images
            - run: docker run -d -p 2181:2181 wurstmeister/zookeeper
            - run: docker run -d -p 9092:9092 wurstmeister/kafka:latest
            - run: docker ps
            - run: sh scripts/kafka.sh
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test