version: 2.1
executors:
  default:
    docker:
      - image: cypress/base
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/beaconsproject
    environment:
      PRODUCTION: false
      PROJECT_NAME: beaconsprojet
      PROJECT_VERSION: 1.0
      GIT: https://github.com/issarompion/beaconsproject.git
      DB_PORT: 27017
      DB_URL: mongodb://localhost
      DB_NAME: beaconsproject
      API_URL: localhost
      API_PORT: 3000
      KAFKA_URL: localhost
      KAFKA_PORT: 9092
      KAFKA_TOPIC_AUTH: auth
      KAFKA_TOPIC_BEACON: beacon
      KAFKA_TOPIC_CLIENT: client
      KAFKA_TOPIC_CONTENT: content
      KAFKA_TOPIC_LOGGER: logger
      KAFKA_REQUEST: req
      KAFKA_RESPONSE: res
      KAFKA_ACTION_LIST: list
      KAFKA_ACTION_READ: read
      KAFKA_ACTION_UPDATE: update
      KAFKA_ACTION_DELETE: delete
      KAFKA_ACTION_CREATE: create
      KAFKA_ACTION_LOGIN: login
      KAFKA_ACTION_LOGOUT: logout
      JWT_KEY: beaconsproject
jobs:
  build-test-back:
    executor: default
    steps:
      - run: set > ".env"
      - run: npm install && ls
      - run: chmod 744 scripts/build_back.sh && chmod 744 scripts/run_back.sh
      - run: sh ./scripts/build_back.sh $DOCKERHUB_USERNAME $PROJECT_VERSION $GIT $API_PORT
      - run: sh ./scripts/run_back.sh $DOCKERHUB_USERNAME $PROJECT_VERSION $API_PORT
      - run: ./node_modules/.bin/wait-on http://$API_URL:$API_PORT && npm run cy:run:back

  deploy-back:
    executor: default
    steps:
        - checkout
        - run: echo "$DOCKERHUB_PASS" && echo "$DOCKERHUB_USERNAME"

  build-test-app:
    executor: default
    steps: 
      - checkout
      - run: npm install
      - run: npm run build:app
      - run: npm run test:app

  deploy-app:
    executor: default
    steps:
      - checkout
      - run: echo "$DOCKERHUB_PASS" && echo "$DOCKERHUB_USERNAME"
  
  build-test-beaconer:
    executor: default
    steps:
      - checkout
      - run: npm install
      - run: npm run build:beaconer
      - run: npm run test:beaconer
  
  deploy-beaconer:
    executor: default
    steps:
      - checkout
      - run: echo "$DOCKERHUB_PASS" && echo "$DOCKERHUB_USERNAME"

workflows:
  version: 2
  build-test-deploy:
      jobs:

        - build-test-back

        - deploy-back:
            requires:
              - build-test-back

        - build-test-app
          - deploy-app:
            requires:
            - build-test-app

        - build-test-beaconer
        - deploy-beaconer:
            requires:
            - build-test-beaconer