version: 2.1
jobs:
  build-and-test:
    docker:
      - images: circleci/node:13.3.0
      - image: wurstmeister/zookeeper
      - image: wurstmeister/kafka:latest
        environment:
          KAFKA_ADVERTISED_HOST_NAME: localhost
          KAFKA_ADVERTISED_PORT: 9092
          KAFKA_PORT: 9092
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
          KAFKA_CREATE_TOPICS: "auth:1:1,client:1:1,beacon:1:1,content:1:1,logger:1:1"

    environment:
      KAFKA_TOPIC_BEACON: beacon
      KAFKA_HOME: opt/kafka

    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: export PROJECT_PATH=$(pwd)
            - run: printenv
            - run: sh scripts/kafka.sh 
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test


